title: Jiboli
author: João Henrique Riboli
email: joao.riboli@outlook.com  
description: Conheça essa figura, não existe botão para desver, esteje avisado!

# social links
twitter_username: ojiboli
github_username:  jiboli
rss: rss
facebook_username: joaohenrique.riboli
instagram_username: jiboli
pinterest_username: jiboli

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %d, %y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - portfolio.md
  - blog.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
