# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "purple" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 1 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 0 # for disable sidebar and sidebar button change to 0
  preloader: "Carregando..." # preloader loading text

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Todos"
      slug: "box-item"
      active: 1

    - name: "Vídeos"
      slug: "f-video"
      active: 0

    #- name: "Música"
    #  slug: "f-music"
    #  active: 0

   # - name: "Links"
   #   slug: "f-link"
   #   active: 0

    - name: "Ilustrações"
      slug: "f-image"
      active: 0

   # - name: "Galeria"
   #   slug: "f-gallery"
   #   active: 0

    - name: "Sites"
      slug: "f-content"
      active: 0
